// cinegrain v2 — Tile-pool grain shader
// Grain tiles pre-generated by Newson-style synthesis (tools/generate_grain_tiles.py).
// This shader only distributes and applies them — near-zero GPU cost.
//
// Architecture:
// - GRAIN_ATLAS: 2×2 grid of 512×512 tiles (1024×1024, 1 channel)
// - Per 32×32 output block: random tile + mirror/rotation + offset
// - Luminance weighting via analytical function (LUT version TBD)

//!PARAM INTENSITY
//!DESC Overall grain strength
//!TYPE float
//!MINIMUM 0.0
//!MAXIMUM 2.0
0.09

//!PARAM PEAK
//!DESC Luminance where grain is strongest (0.0-1.0)
//!TYPE float
//!MINIMUM 0.0
//!MAXIMUM 1.0
0.40

//!PARAM ROLLOFF
//!DESC Bell curve width (larger = wider/flatter)
//!TYPE float
//!MINIMUM 0.01
//!MAXIMUM 2.0
0.40

//!PARAM CHROMA
//!DESC Colour grain strength (R/B shift, film-style)
//!TYPE float
//!MINIMUM 0.0
//!MAXIMUM 1.0
0.05

//!HOOK OUTPUT
//!BIND HOOKED
//!BIND GRAIN_ATLAS
//!DESC cinegrain2

// Block size for tile assignment (pixels)
#define BLOCK_SIZE 32

// Atlas layout: 2×2 tiles, each 512×512 in a 1024×1024 texture
#define ATLAS_COLS 2
#define TILE_SIZE 512.0

// Hash for block → tile assignment (fast integer hash)
uint block_hash(ivec2 block, uint seed)
{
    uint h = uint(block.x) * 1103515245u + uint(block.y) * 12345u + seed;
    h ^= h >> 16u;
    h *= 0x45d9f3bu;
    h ^= h >> 16u;
    h *= 0x45d9f3bu;
    h ^= h >> 16u;
    return h;
}

// Asymmetric bell curve — same as v1
float luma_weight(float luma)
{
    float r = (luma > PEAK) ? ROLLOFF * 0.35 : ROLLOFF;
    float d = (luma - PEAK) / r;
    float bell = exp(-0.5 * d * d);
    float shadow = min(pow(luma / max(PEAK, 0.001), 0.18), 1.0) * smoothstep(0.0, 0.03, luma);
    return bell * shadow;
}

// Apply mirror + rotation variant to UV coordinates
vec2 apply_variant(vec2 uv, uint variant)
{
    // bit 0: horizontal mirror
    if ((variant & 1u) != 0u) uv.x = 1.0 - uv.x;
    // bit 1-2: rotation (0, 90, 180, 270)
    uint rot = (variant >> 1u) & 3u;
    if (rot == 1u) uv = vec2(1.0 - uv.y, uv.x);        // 90°
    else if (rot == 2u) uv = vec2(1.0 - uv.x, 1.0 - uv.y); // 180°
    else if (rot == 3u) uv = vec2(uv.y, 1.0 - uv.x);    // 270°
    return uv;
}

vec4 hook()
{
    vec4 color = HOOKED_tex(HOOKED_pos);

    // Which block are we in?
    ivec2 pixel = ivec2(gl_FragCoord.xy);
    ivec2 block = pixel / BLOCK_SIZE;

    // Hash → tile index + variant + offset
    uint seed = uint(random * 4294967295.0);  // frame seed
    uint h = block_hash(block, seed);
    uint tile_idx = h & 3u;          // 0–3: which base tile
    uint variant = (h >> 2u) & 7u;   // 0–7: mirror + rotation
    vec2 offset = vec2(float((h >> 5u) & 255u), float((h >> 13u) & 255u)) / 256.0;

    // Position within block → UV in tile [0, 1]
    vec2 block_pos = vec2(pixel - block * BLOCK_SIZE) / TILE_SIZE;
    vec2 tile_uv = fract(block_pos + offset);

    // Apply mirror/rotation
    tile_uv = apply_variant(tile_uv, variant);

    // Map to atlas UV
    float tile_col = float(tile_idx % ATLAS_COLS);
    float tile_row = float(tile_idx / ATLAS_COLS);
    vec2 atlas_uv = (vec2(tile_col, tile_row) + tile_uv) / vec2(float(ATLAS_COLS), float(ATLAS_COLS));

    // Grain lookup
    float grain = (GRAIN_ATLAS_tex(atlas_uv).r - 0.5) * 2.0;

    // Luminance weighting
    float luma = dot(color.rgb, vec3(0.2126, 0.7152, 0.0722));
    float weight = luma_weight(luma);

    color.rgb += vec3(INTENSITY * weight * grain);

    // Chroma grain (derived from luma grain with offset — cheap)
    if (CHROMA > 0.0) {
        vec2 chroma_uv = fract(tile_uv + vec2(0.37, 0.71));  // fixed offset
        chroma_uv = apply_variant(chroma_uv, variant ^ 3u);   // different variant
        vec2 chroma_atlas = (vec2(tile_col, tile_row) + chroma_uv) / vec2(float(ATLAS_COLS), float(ATLAS_COLS));
        float cgrain = (GRAIN_ATLAS_tex(chroma_atlas).r - 0.5) * 2.0;
        float cw = INTENSITY * CHROMA * weight;
        color.r += cw * cgrain;
        color.b -= cw * cgrain * 0.7;  // opposite R/B shift like real film
    }

    color.rgb = max(color.rgb, vec3(0.0));
    return color;
}
